version: '3.8'

services:
  url-postgres:
    image: postgres
    container_name: url-postgres
    environment:
      POSTGRES_PASSWORD: urlshortner6801
    ports:
    - "5433:5432"
  
  url-redis:
    image: redis
    container_name: url-redis
    environment:
      - REDIS_PASSWORD=redis6801
    ports:
      - "6379:6379"
  
  fastapi-app:
    build: ./backend
    deploy:
      replicas: 3
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    depends_on:
      - url-postgres
      - url-redis

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - fastapi-app
