events {}

http {
    upstream backend_cluster {
        server fastapi-app:8000;
    }
    server {
        # 1. Listen on Port 80 (The standard internet HTTP port)
        listen 80;

        # 2. When someone goes to the root of the website ("/")
        location / {
            # 3. Forward the traffic to our FastAPI container using Docker's internal DNS
            proxy_pass http://backend_cluster;
            
            # 4. Pass along the original Host name
            proxy_set_header Host $host;
            
            # 5. Pass along the user's REAL IP Address
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
