name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build and deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Copy files to EC2 via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ubuntu
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          source: "."
          target: "Url-Shortner-Project"

      - name: Rebuild Docker Containers via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ubuntu
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          script: |
            cd Url-Shortner-Project
            echo "NEXT_PUBLIC_API_URL=http://${{ secrets.AWS_HOST }}:80" > url-shortner/.env.production
            echo "DATABASE_URL=postgresql://postgres:urlshortner6801@url-postgres:5432/postgres" > backend/.env
            sudo docker compose up -d --build